name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Helm
        uses: azure/setup-helm@v1

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: ./charts
          release_branch: gh-pages
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update index.yaml
        run: |
          mkdir -p docs
          cp -r .cr-release-packages/* docs/
          helm repo index docs --url https://<YOUR_GITHUB_USERNAME>.github.io/<YOUR_REPOSITORY_NAME> --merge docs/index.yaml
          
      - name: Push changes to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
